name: swipeable_page_route_example
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  swipeable_page_route:
    path: ../

dev_dependencies:
  build_runner: ^2.4.15
  go_router_builder: ^2.8.2
  supernova_lints:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova_lints
      ref: 797fee80506223c712e232017ac705336eecedf2

flutter:
  uses-material-design: true
